{% set name = "lipyds" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lipyds-{{ version }}.tar.gz
  sha256: 9de55a125a3c3d6b9061cdc1fac3f1d502dab5bd6df408edf0e63e8a3dc7022d

build:
  skip: true  # [win or py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython >=0.28
    - setuptools
    - numpy >=2.0.0
    - versioningit
    - pip
  run:
    - python
    - mdanalysis >=2.0.0
    - networkx

test:
  imports:
    - lipyds
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/lilyminium/lipyds
  summary: A toolkit for leaflet-based membrane analysis
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lilyminium
